package com.test.drl;
unit PolicyUnit;

rule "ff80818199f0baa40199f1aa035300af"
	salience -200
	when
		result: /results[ this != null ]
		/eventTypes[ event == "PAYMENT" , customEvent == "CORP_APP_EXTERNAL_TRANSFER" || event == "PAYMENT" , customEvent == "CORP_APP_IBAN2IBAN_TRANSFER" || event == "PAYMENT" , customEvent == "CORP_APP_INTERNAL_TRANSFER" || event == "PAYMENT" , customEvent == "CORP_EXTERNAL_TRANSFER" || event == "PAYMENT" , customEvent == "CORP_IBAN2IBAN_TRANSFER" || event == "PAYMENT" , customEvent == "CORP_INTERNAL_TRANSFER" || event == "PAYMENT" , customEvent == null ]
		/channels[ channelIndicator == "WEB" || channelIndicator == "MOBILE" ]
		/configurationFact[ name == "userIdMasking", userIdMaskingValue: value ]
		and /configurationFact[ name == "listIdMasking", listIdMaskingValue: value ]
		and /configurationFact[ name == "orgName", orgNameValue: value ]
		and /configurationFact[ name == "tenantId", tenantIdValue: value ]
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_SCORING)", value  >= 200 && value <= 300 ]) )
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", valueStr != null, valueStr.contains("R21") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)", valueStr != null, valueStr.contains("R22") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)", valueStr != null, valueStr.contains("R23") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP4)", valueStr != null, valueStr.contains("R24") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", valueStr != null, valueStr.contains("R31") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)", valueStr != null, valueStr.contains("R32") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)", valueStr != null, valueStr.contains("R33") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP4)", valueStr != null, valueStr.contains("R34") ]) )
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", valueStr != null, valueStr.contains("R41") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)", valueStr != null, valueStr.contains("R42") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)", valueStr != null, valueStr.contains("R43") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP4)", valueStr != null, valueStr.contains("R44") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", valueStr != null, valueStr.contains("R51") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)", valueStr != null, valueStr.contains("R52") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)", valueStr != null, valueStr.contains("R53") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP4)", valueStr != null, valueStr.contains("R54") ]) )
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", valueStr != null, valueStr.contains("R61") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)", valueStr != null, valueStr.contains("R62") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)", valueStr != null, valueStr.contains("R63") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", valueStr != null, valueStr.contains("R71") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)", valueStr != null, valueStr.contains("R72") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)", valueStr != null, valueStr.contains("R73") ]) )
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", valueStr != null, valueStr.contains("R81") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)", valueStr != null, valueStr.contains("R82") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)", valueStr != null, valueStr.contains("R83") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP4)", valueStr != null, valueStr.contains("R84") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", valueStr != null, valueStr.contains("R91") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)", valueStr != null, valueStr.contains("R92") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)", valueStr != null, valueStr.contains("R93") ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP4)", valueStr != null, valueStr.contains("R94") ]) )
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BANK_ID)", val61: value, tp61: type ]
		 and eval( listManager.isValueInList(val61, tp61, "ff80818194cc4bf60194cce11cfe001f", (Boolean)userIdMaskingValue, (Boolean)listIdMaskingValue, (String)orgNameValue, (String)tenantIdValue) ))
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BANK_ID)", value == "3" ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(RSA_DECLINES)", value >= 3 ]) )
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(RSA_DECLINES)", value > 2 ]) )
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_SCORING)", value == 1 ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", value != "2" ])
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)", val83: value, tp83: type ]
		 and eval( listManager.isValueInList(val83, tp83, "ff8081818cc87b39018cc8cdea680002", (Boolean)userIdMaskingValue, (Boolean)listIdMaskingValue, (String)orgNameValue, (String)tenantIdValue) ))
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)", val84: value, tp84: type ]
		 and eval( listManager.containsListValue(val84, tp84, "ff80818194d60fa60194d61aaa29006a", (Boolean)userIdMaskingValue, (Boolean)listIdMaskingValue, (String)orgNameValue, (String)tenantIdValue) ))
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP4)", val85: value, tp85: type ]
		 and eval(! listManager.isValueInList(val85, tp85, "ff80818194cc4bf60194cce11cfe001f", (Boolean)userIdMaskingValue, (Boolean)listIdMaskingValue, (String)orgNameValue, (String)tenantIdValue) )) )
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BANK_ID)", valueStr != null, valueStr.contains("abc") ])
		 or /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_SCORING)" , v192 : value ]
		 and /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(intfact)" , v192 >= value ]
		 or ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP1)", valueStr != null, !valueStr.contains("abc") ])
		 or ( not /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP2)" ] )
		 or /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP3)" , v195 : value ]
		 and /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BANK_ID)" , v195 == value ] )
		( ( /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(POLICY_ACTION)", value == "ACTION" ])
		 or /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BIOCATCH_TOP4)", factval102: valueStr, factval102 != null ]
		 and /facts [ name == "transaction.current.event.current.clientDefinedFacts.value(BANK_ID)", otherfactval102: valueStr, otherfactval102 != null, otherfactval102.contains(factval102) ] )
	then
		result.addFiredProductionRule("ff80818199f0baa40199f1aa035300af");
end
